dist: xenial
language: node_js
node_js:
  - 'lts/dubnium'
install:
  - npm ci
script:
  - ganache-cli > /dev/null &
  - sleep 5
  - npm run migrate
  - npm run test
  - npm run coverage
after_success:
  - bash <(curl -s https://codecov.io/bash) -t 10300c39-4ccc-419e-9b5b-4849de32d025
