dist: xenial
language: node_js
node_js:
  - 'lts/dubnium'
install:
  - npm ci
script:
  - ganache-cli > /dev/null &
  - sleep 5
  - npm run migrate
  - npm run test
  - npm run coverage
  - npx codechecks
