/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { EventData, PastEventOptions } from "web3-eth-contract";

export interface CampaignV2Contract
  extends Truffle.Contract<CampaignV2Instance> {
  "new"(meta?: Truffle.TransactionDetails): Promise<CampaignV2Instance>;
}

export interface CampaignDeadlineExtended {
  name: "CampaignDeadlineExtended";
  args: {
    campaignId: BN;
    time: BN;
    sender: string;
    0: BN;
    1: BN;
    2: string;
  };
}

export interface CampaignOwnerSet {
  name: "CampaignOwnerSet";
  args: {
    campaignId: BN;
    user: string;
    sender: string;
    0: BN;
    1: string;
    2: string;
  };
}

export interface CampaignOwnershipTransferred {
  name: "CampaignOwnershipTransferred";
  args: {
    campaignId: BN;
    newUser: string;
    sender: string;
    0: BN;
    1: string;
    2: string;
  };
}

export interface CampaignReported {
  name: "CampaignReported";
  args: {
    campaignId: BN;
    sender: string;
    0: BN;
    1: string;
  };
}

export interface CampaignReviewed {
  name: "CampaignReviewed";
  args: {
    campaignId: BN;
    sender: string;
    0: BN;
    1: string;
  };
}

export interface CampaignSettingsUpdated {
  name: "CampaignSettingsUpdated";
  args: {
    campaignId: BN;
    minimumContribution: BN;
    deadline: BN;
    goalType: BN;
    token: string;
    sender: string;
    0: BN;
    1: BN;
    2: BN;
    3: BN;
    4: string;
    5: string;
  };
}

export interface CampaignStateChange {
  name: "CampaignStateChange";
  args: {
    campaignId: BN;
    state: BN;
    sender: string;
    0: BN;
    1: BN;
    2: string;
  };
}

export interface CampaignUserDataTransferred {
  name: "CampaignUserDataTransferred";
  args: {
    campaignId: BN;
    oldAddress: string;
    newAddress: string;
    sender: string;
    0: BN;
    1: string;
    2: string;
    3: string;
  };
}

export interface ContributionMade {
  name: "ContributionMade";
  args: {
    campaignId: BN;
    amount: BN;
    sender: string;
    0: BN;
    1: BN;
    2: string;
  };
}

export interface ContributionWithdrawn {
  name: "ContributionWithdrawn";
  args: {
    campaignId: BN;
    amount: BN;
    user: string;
    sender: string;
    0: BN;
    1: BN;
    2: string;
    3: string;
  };
}

export interface Paused {
  name: "Paused";
  args: {
    account: string;
    0: string;
  };
}

export interface RequestAdded {
  name: "RequestAdded";
  args: {
    requestId: BN;
    campaignId: BN;
    duration: BN;
    value: BN;
    recipient: string;
    sender: string;
    0: BN;
    1: BN;
    2: BN;
    3: BN;
    4: string;
    5: string;
  };
}

export interface RequestComplete {
  name: "RequestComplete";
  args: {
    requestId: BN;
    campaignId: BN;
    sender: string;
    0: BN;
    1: BN;
    2: string;
  };
}

export interface RequestVoided {
  name: "RequestVoided";
  args: {
    requestId: BN;
    campaignId: BN;
    sender: string;
    0: BN;
    1: BN;
    2: string;
  };
}

export interface RoleAdminChanged {
  name: "RoleAdminChanged";
  args: {
    role: string;
    previousAdminRole: string;
    newAdminRole: string;
    0: string;
    1: string;
    2: string;
  };
}

export interface RoleGranted {
  name: "RoleGranted";
  args: {
    role: string;
    account: string;
    sender: string;
    0: string;
    1: string;
    2: string;
  };
}

export interface RoleRevoked {
  name: "RoleRevoked";
  args: {
    role: string;
    account: string;
    sender: string;
    0: string;
    1: string;
    2: string;
  };
}

export interface TargetMet {
  name: "TargetMet";
  args: {
    campaignId: BN;
    amount: BN;
    sender: string;
    0: BN;
    1: BN;
    2: string;
  };
}

export interface Unpaused {
  name: "Unpaused";
  args: {
    account: string;
    0: string;
  };
}

export interface VoteCancelled {
  name: "VoteCancelled";
  args: {
    requestId: BN;
    support: BN;
    campaignId: BN;
    sender: string;
    0: BN;
    1: BN;
    2: BN;
    3: string;
  };
}

export interface Voted {
  name: "Voted";
  args: {
    requestId: BN;
    support: BN;
    campaignId: BN;
    sender: string;
    0: BN;
    1: BN;
    2: BN;
    3: string;
  };
}

type AllEvents =
  | CampaignDeadlineExtended
  | CampaignOwnerSet
  | CampaignOwnershipTransferred
  | CampaignReported
  | CampaignReviewed
  | CampaignSettingsUpdated
  | CampaignStateChange
  | CampaignUserDataTransferred
  | ContributionMade
  | ContributionWithdrawn
  | Paused
  | RequestAdded
  | RequestComplete
  | RequestVoided
  | RoleAdminChanged
  | RoleGranted
  | RoleRevoked
  | TargetMet
  | Unpaused
  | VoteCancelled
  | Voted;

export interface CampaignV2Instance extends Truffle.ContractInstance {
  DEFAULT_ADMIN_ROLE(txDetails?: Truffle.TransactionDetails): Promise<string>;

  acceptedToken(txDetails?: Truffle.TransactionDetails): Promise<string>;

  allowContributionAfterTargetIsMet(
    txDetails?: Truffle.TransactionDetails
  ): Promise<boolean>;

  approvers(
    arg0: string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<boolean>;

  approversCount(txDetails?: Truffle.TransactionDetails): Promise<BN>;

  campaignBalance(txDetails?: Truffle.TransactionDetails): Promise<BN>;

  campaignID(txDetails?: Truffle.TransactionDetails): Promise<BN>;

  campaignState(txDetails?: Truffle.TransactionDetails): Promise<BN>;

  currentRunningRequest(txDetails?: Truffle.TransactionDetails): Promise<BN>;

  deadline(txDetails?: Truffle.TransactionDetails): Promise<BN>;

  deadlineSetTimes(txDetails?: Truffle.TransactionDetails): Promise<BN>;

  finalizedRequestCount(txDetails?: Truffle.TransactionDetails): Promise<BN>;

  /**
   * Returns the admin role that controls `role`. See {grantRole} and {revokeRole}. To change a role's admin, use {_setRoleAdmin}.
   */
  getRoleAdmin(
    role: string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<string>;

  goalType(txDetails?: Truffle.TransactionDetails): Promise<BN>;

  /**
   * Grants `role` to `account`. If `account` had not been already granted `role`, emits a {RoleGranted} event. Requirements: - the caller must have ``role``'s admin role.
   */
  grantRole: {
    (
      role: string,
      account: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse<AllEvents>>;
    call(
      role: string,
      account: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      role: string,
      account: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      role: string,
      account: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  /**
   * Returns `true` if `account` has been granted `role`.
   */
  hasRole(
    role: string,
    account: string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<boolean>;

  hasVoted(
    arg0: number | BN | string,
    arg1: string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<boolean>;

  minimumContribution(txDetails?: Truffle.TransactionDetails): Promise<BN>;

  /**
   * Returns true if the contract is paused, and false otherwise.
   */
  paused(txDetails?: Truffle.TransactionDetails): Promise<boolean>;

  /**
   * Revokes `role` from the calling account. Roles are often managed via {grantRole} and {revokeRole}: this function's purpose is to provide a mechanism for accounts to lose their privileges if they are compromised (such as when a trusted device is misplaced). If the calling account had been granted `role`, emits a {RoleRevoked} event. Requirements: - the caller must be `account`.
   */
  renounceRole: {
    (
      role: string,
      account: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse<AllEvents>>;
    call(
      role: string,
      account: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      role: string,
      account: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      role: string,
      account: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  reportCount(txDetails?: Truffle.TransactionDetails): Promise<BN>;

  reported(
    arg0: string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<boolean>;

  requestCount(txDetails?: Truffle.TransactionDetails): Promise<BN>;

  requestSupport(
    arg0: number | BN | string,
    arg1: string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<BN>;

  requests(
    arg0: number | BN | string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<{
    0: string;
    1: boolean;
    2: BN;
    3: BN;
    4: BN;
    5: BN;
    6: BN;
    7: boolean;
  }>;

  reviewCount(txDetails?: Truffle.TransactionDetails): Promise<BN>;

  reviewed(
    arg0: string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<boolean>;

  /**
   * Revokes `role` from `account`. If `account` had been granted `role`, emits a {RoleRevoked} event. Requirements: - the caller must have ``role``'s admin role.
   */
  revokeRole: {
    (
      role: string,
      account: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse<AllEvents>>;
    call(
      role: string,
      account: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      role: string,
      account: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      role: string,
      account: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  root(txDetails?: Truffle.TransactionDetails): Promise<string>;

  /**
   * See {IERC165-supportsInterface}.
   */
  supportsInterface(
    interfaceId: string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<boolean>;

  target(txDetails?: Truffle.TransactionDetails): Promise<BN>;

  totalCampaignContribution(
    txDetails?: Truffle.TransactionDetails
  ): Promise<BN>;

  userContributionWithdrawn(
    arg0: string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<boolean>;

  userTotalContribution(
    arg0: string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<BN>;

  withdrawalsPaused(txDetails?: Truffle.TransactionDetails): Promise<boolean>;

  /**
   * Constructor
   * @param _campaignFactory Address of factory
   * @param _root Address of campaign owner
   */
  __Campaign_init: {
    (
      _campaignFactory: string,
      _root: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse<AllEvents>>;
    call(
      _campaignFactory: string,
      _root: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      _campaignFactory: string,
      _root: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      _campaignFactory: string,
      _root: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  /**
   * Transfers campaign ownership from one user to another.
   * @param _newRoot Address of the user campaign ownership is being transfered to
   */
  transferCampaignOwnership: {
    (_newRoot: string, txDetails?: Truffle.TransactionDetails): Promise<
      Truffle.TransactionResponse<AllEvents>
    >;
    call(
      _newRoot: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      _newRoot: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      _newRoot: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  /**
   * Transfers user data in the campaign to another verifed user
   * @param _newAddress Address of the user being transferred to
   * @param _oldAddress Address of the user transferring
   */
  transferCampaignUserData: {
    (
      _oldAddress: string,
      _newAddress: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse<AllEvents>>;
    call(
      _oldAddress: string,
      _newAddress: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      _oldAddress: string,
      _newAddress: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      _oldAddress: string,
      _newAddress: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  /**
   * Modifies campaign details while it's not approved
   * @param _allowContributionAfterTargetIsMet Indicates if the campaign can receive contributions after duration expires
   * @param _duration How long until the campaign stops receiving contributions
   * @param _goalType If flexible the campaign owner is able to create requests if targe isn't met, fixed opposite
   * @param _minimumContribution The minimum amout required to be an approver
   * @param _target Contribution target of the campaign
   * @param _token Address of token to be used for transactions by default
   */
  setCampaignSettings: {
    (
      _target: number | BN | string,
      _minimumContribution: number | BN | string,
      _duration: number | BN | string,
      _goalType: number | BN | string,
      _token: string,
      _allowContributionAfterTargetIsMet: boolean,
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse<AllEvents>>;
    call(
      _target: number | BN | string,
      _minimumContribution: number | BN | string,
      _duration: number | BN | string,
      _goalType: number | BN | string,
      _token: string,
      _allowContributionAfterTargetIsMet: boolean,
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      _target: number | BN | string,
      _minimumContribution: number | BN | string,
      _duration: number | BN | string,
      _goalType: number | BN | string,
      _token: string,
      _allowContributionAfterTargetIsMet: boolean,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      _target: number | BN | string,
      _minimumContribution: number | BN | string,
      _duration: number | BN | string,
      _goalType: number | BN | string,
      _token: string,
      _allowContributionAfterTargetIsMet: boolean,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  /**
   * Extends campaign contribution deadline
   * @param _time How long until the campaign stops receiving contributions
   */
  extendDeadline: {
    (
      _time: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse<AllEvents>>;
    call(
      _time: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      _time: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      _time: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  /**
   * Sets the number of times the campaign owner can extended deadlines. Restricted to factory
   * @param _count Number of times a campaign owner can extend the deadline
   */
  setDeadlineSetTimes: {
    (
      _count: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse<AllEvents>>;
    call(
      _count: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      _count: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      _count: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  /**
   * Contribute method enables a user become an approver in the campaign
   * @param _rewardId Reward unique id
   * @param _token Address of token to be used for transactions by default
   * @param _withReward Indicates if the user wants a reward alongside their contribution
   */
  contribute: {
    (
      _token: string,
      _rewardId: number | BN | string,
      _withReward: boolean,
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse<AllEvents>>;
    call(
      _token: string,
      _rewardId: number | BN | string,
      _withReward: boolean,
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      _token: string,
      _rewardId: number | BN | string,
      _withReward: boolean,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      _token: string,
      _rewardId: number | BN | string,
      _withReward: boolean,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  /**
   * Allows withdrawal of contribution by a user, works if campaign target isn't met
   * @param _wallet Address where amount is delivered
   */
  withdrawOwnContribution: {
    (_wallet: string, txDetails?: Truffle.TransactionDetails): Promise<
      Truffle.TransactionResponse<AllEvents>
    >;
    call(
      _wallet: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      _wallet: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      _wallet: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  /**
   * Allows withdrawal of balance by factory on behalf of a user.  Cases where users wallet is compromised
   * @param _user User whose funds are being requested
   * @param _wallet Address where amount is delivered
   */
  withdrawContributionForUser: {
    (
      _user: string,
      _wallet: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse<AllEvents>>;
    call(
      _user: string,
      _wallet: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      _user: string,
      _wallet: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      _user: string,
      _wallet: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  /**
   * Used to measure user funds left after request finalizations
   * @param _user Address of user check is carried out on
   */
  userContributionLoss(
    _user: string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<BN>;

  /**
   * Creates a formal request to withdraw funds from user contributions called by the campagn manager or factory Restricted unless target is met and deadline is expired
   * @param _duration Duration until users aren't able to vote on the request
   * @param _recipient Address where requested funds are deposited
   * @param _value Amount being requested by the campaign manager
   */
  createRequest: {
    (
      _recipient: string,
      _value: number | BN | string,
      _duration: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse<AllEvents>>;
    call(
      _recipient: string,
      _value: number | BN | string,
      _duration: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      _recipient: string,
      _value: number | BN | string,
      _duration: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      _recipient: string,
      _value: number | BN | string,
      _duration: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  /**
   * Renders a request void and useless
   * @param _requestId ID of request being voided
   */
  voidRequest: {
    (
      _requestId: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse<AllEvents>>;
    call(
      _requestId: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      _requestId: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      _requestId: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  /**
   * Approvers only method which approves spending request issued by the campaign manager or factory
   * @param _requestId ID of request being voted on
   * @param _support An integer of 0 for against, 1 for in-favor, and 2 for abstain
   */
  voteOnRequest: {
    (
      _requestId: number | BN | string,
      _support: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse<AllEvents>>;
    call(
      _requestId: number | BN | string,
      _support: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      _requestId: number | BN | string,
      _support: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      _requestId: number | BN | string,
      _support: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  /**
   * Approvers only method which cancels initial vote on a request
   * @param _requestId ID of request being voted on
   */
  cancelVote: {
    (
      _requestId: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse<AllEvents>>;
    call(
      _requestId: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      _requestId: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      _requestId: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  /**
   * Withdrawal method called only when a request receives the right amount votes
   * @param _requestId ID of request being withdrawn
   */
  finalizeRequest: {
    (
      _requestId: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse<AllEvents>>;
    call(
      _requestId: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      _requestId: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      _requestId: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  /**
   * Pauses the campaign and switches `campaignState` to `REVIEW` indicating it's ready to be reviewd by it's approvers after the campaign is over
   */
  reviewMode: {
    (txDetails?: Truffle.TransactionDetails): Promise<
      Truffle.TransactionResponse<AllEvents>
    >;
    call(txDetails?: Truffle.TransactionDetails): Promise<void>;
    sendTransaction(txDetails?: Truffle.TransactionDetails): Promise<string>;
    estimateGas(txDetails?: Truffle.TransactionDetails): Promise<number>;
  };

  /**
   * User acknowledgement of review state enabled by the campaign owner
   */
  reviewCampaignPerformance: {
    (txDetails?: Truffle.TransactionDetails): Promise<
      Truffle.TransactionResponse<AllEvents>
    >;
    call(txDetails?: Truffle.TransactionDetails): Promise<void>;
    sendTransaction(txDetails?: Truffle.TransactionDetails): Promise<string>;
    estimateGas(txDetails?: Truffle.TransactionDetails): Promise<number>;
  };

  /**
   * Called by campaign manager to mark the campaign as complete right after it secured enough reviews from users
   */
  markCampaignComplete: {
    (txDetails?: Truffle.TransactionDetails): Promise<
      Truffle.TransactionResponse<AllEvents>
    >;
    call(txDetails?: Truffle.TransactionDetails): Promise<void>;
    sendTransaction(txDetails?: Truffle.TransactionDetails): Promise<string>;
    estimateGas(txDetails?: Truffle.TransactionDetails): Promise<number>;
  };

  /**
   * Called by an approver to report a campaign to factory. Campaign must be in collection or live state
   */
  reportCampaign: {
    (txDetails?: Truffle.TransactionDetails): Promise<
      Truffle.TransactionResponse<AllEvents>
    >;
    call(txDetails?: Truffle.TransactionDetails): Promise<void>;
    sendTransaction(txDetails?: Truffle.TransactionDetails): Promise<string>;
    estimateGas(txDetails?: Truffle.TransactionDetails): Promise<number>;
  };

  /**
   * Changes campaign state
   */
  setCampaignState: {
    (
      _state: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse<AllEvents>>;
    call(
      _state: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      _state: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      _state: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  /**
   * Pauses or Unpauses withdrawals depending on state passed in argument
   * @param _state Indicates pause or unpause state
   */
  toggleWithdrawalState: {
    (_state: boolean, txDetails?: Truffle.TransactionDetails): Promise<
      Truffle.TransactionResponse<AllEvents>
    >;
    call(
      _state: boolean,
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      _state: boolean,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      _state: boolean,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  /**
   * Unpauses the campaign, transactions in the campaign resume per usual
   */
  unpauseCampaign: {
    (txDetails?: Truffle.TransactionDetails): Promise<
      Truffle.TransactionResponse<AllEvents>
    >;
    call(txDetails?: Truffle.TransactionDetails): Promise<void>;
    sendTransaction(txDetails?: Truffle.TransactionDetails): Promise<string>;
    estimateGas(txDetails?: Truffle.TransactionDetails): Promise<number>;
  };

  /**
   * Pauses the campaign, it halts all transactions in the campaign
   */
  pauseCampaign: {
    (txDetails?: Truffle.TransactionDetails): Promise<
      Truffle.TransactionResponse<AllEvents>
    >;
    call(txDetails?: Truffle.TransactionDetails): Promise<void>;
    sendTransaction(txDetails?: Truffle.TransactionDetails): Promise<string>;
    estimateGas(txDetails?: Truffle.TransactionDetails): Promise<number>;
  };

  methods: {
    DEFAULT_ADMIN_ROLE(txDetails?: Truffle.TransactionDetails): Promise<string>;

    acceptedToken(txDetails?: Truffle.TransactionDetails): Promise<string>;

    allowContributionAfterTargetIsMet(
      txDetails?: Truffle.TransactionDetails
    ): Promise<boolean>;

    approvers(
      arg0: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<boolean>;

    approversCount(txDetails?: Truffle.TransactionDetails): Promise<BN>;

    campaignBalance(txDetails?: Truffle.TransactionDetails): Promise<BN>;

    campaignID(txDetails?: Truffle.TransactionDetails): Promise<BN>;

    campaignState(txDetails?: Truffle.TransactionDetails): Promise<BN>;

    currentRunningRequest(txDetails?: Truffle.TransactionDetails): Promise<BN>;

    deadline(txDetails?: Truffle.TransactionDetails): Promise<BN>;

    deadlineSetTimes(txDetails?: Truffle.TransactionDetails): Promise<BN>;

    finalizedRequestCount(txDetails?: Truffle.TransactionDetails): Promise<BN>;

    /**
     * Returns the admin role that controls `role`. See {grantRole} and {revokeRole}. To change a role's admin, use {_setRoleAdmin}.
     */
    getRoleAdmin(
      role: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;

    goalType(txDetails?: Truffle.TransactionDetails): Promise<BN>;

    /**
     * Grants `role` to `account`. If `account` had not been already granted `role`, emits a {RoleGranted} event. Requirements: - the caller must have ``role``'s admin role.
     */
    grantRole: {
      (
        role: string,
        account: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<Truffle.TransactionResponse<AllEvents>>;
      call(
        role: string,
        account: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        role: string,
        account: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        role: string,
        account: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    /**
     * Returns `true` if `account` has been granted `role`.
     */
    hasRole(
      role: string,
      account: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<boolean>;

    hasVoted(
      arg0: number | BN | string,
      arg1: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<boolean>;

    minimumContribution(txDetails?: Truffle.TransactionDetails): Promise<BN>;

    /**
     * Returns true if the contract is paused, and false otherwise.
     */
    paused(txDetails?: Truffle.TransactionDetails): Promise<boolean>;

    /**
     * Revokes `role` from the calling account. Roles are often managed via {grantRole} and {revokeRole}: this function's purpose is to provide a mechanism for accounts to lose their privileges if they are compromised (such as when a trusted device is misplaced). If the calling account had been granted `role`, emits a {RoleRevoked} event. Requirements: - the caller must be `account`.
     */
    renounceRole: {
      (
        role: string,
        account: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<Truffle.TransactionResponse<AllEvents>>;
      call(
        role: string,
        account: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        role: string,
        account: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        role: string,
        account: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    reportCount(txDetails?: Truffle.TransactionDetails): Promise<BN>;

    reported(
      arg0: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<boolean>;

    requestCount(txDetails?: Truffle.TransactionDetails): Promise<BN>;

    requestSupport(
      arg0: number | BN | string,
      arg1: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<BN>;

    requests(
      arg0: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<{
      0: string;
      1: boolean;
      2: BN;
      3: BN;
      4: BN;
      5: BN;
      6: BN;
      7: boolean;
    }>;

    reviewCount(txDetails?: Truffle.TransactionDetails): Promise<BN>;

    reviewed(
      arg0: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<boolean>;

    /**
     * Revokes `role` from `account`. If `account` had been granted `role`, emits a {RoleRevoked} event. Requirements: - the caller must have ``role``'s admin role.
     */
    revokeRole: {
      (
        role: string,
        account: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<Truffle.TransactionResponse<AllEvents>>;
      call(
        role: string,
        account: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        role: string,
        account: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        role: string,
        account: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    root(txDetails?: Truffle.TransactionDetails): Promise<string>;

    /**
     * See {IERC165-supportsInterface}.
     */
    supportsInterface(
      interfaceId: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<boolean>;

    target(txDetails?: Truffle.TransactionDetails): Promise<BN>;

    totalCampaignContribution(
      txDetails?: Truffle.TransactionDetails
    ): Promise<BN>;

    userContributionWithdrawn(
      arg0: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<boolean>;

    userTotalContribution(
      arg0: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<BN>;

    withdrawalsPaused(txDetails?: Truffle.TransactionDetails): Promise<boolean>;

    /**
     * Constructor
     * @param _campaignFactory Address of factory
     * @param _root Address of campaign owner
     */
    __Campaign_init: {
      (
        _campaignFactory: string,
        _root: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<Truffle.TransactionResponse<AllEvents>>;
      call(
        _campaignFactory: string,
        _root: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        _campaignFactory: string,
        _root: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        _campaignFactory: string,
        _root: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    /**
     * Transfers campaign ownership from one user to another.
     * @param _newRoot Address of the user campaign ownership is being transfered to
     */
    transferCampaignOwnership: {
      (_newRoot: string, txDetails?: Truffle.TransactionDetails): Promise<
        Truffle.TransactionResponse<AllEvents>
      >;
      call(
        _newRoot: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        _newRoot: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        _newRoot: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    /**
     * Transfers user data in the campaign to another verifed user
     * @param _newAddress Address of the user being transferred to
     * @param _oldAddress Address of the user transferring
     */
    transferCampaignUserData: {
      (
        _oldAddress: string,
        _newAddress: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<Truffle.TransactionResponse<AllEvents>>;
      call(
        _oldAddress: string,
        _newAddress: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        _oldAddress: string,
        _newAddress: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        _oldAddress: string,
        _newAddress: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    /**
     * Modifies campaign details while it's not approved
     * @param _allowContributionAfterTargetIsMet Indicates if the campaign can receive contributions after duration expires
     * @param _duration How long until the campaign stops receiving contributions
     * @param _goalType If flexible the campaign owner is able to create requests if targe isn't met, fixed opposite
     * @param _minimumContribution The minimum amout required to be an approver
     * @param _target Contribution target of the campaign
     * @param _token Address of token to be used for transactions by default
     */
    setCampaignSettings: {
      (
        _target: number | BN | string,
        _minimumContribution: number | BN | string,
        _duration: number | BN | string,
        _goalType: number | BN | string,
        _token: string,
        _allowContributionAfterTargetIsMet: boolean,
        txDetails?: Truffle.TransactionDetails
      ): Promise<Truffle.TransactionResponse<AllEvents>>;
      call(
        _target: number | BN | string,
        _minimumContribution: number | BN | string,
        _duration: number | BN | string,
        _goalType: number | BN | string,
        _token: string,
        _allowContributionAfterTargetIsMet: boolean,
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        _target: number | BN | string,
        _minimumContribution: number | BN | string,
        _duration: number | BN | string,
        _goalType: number | BN | string,
        _token: string,
        _allowContributionAfterTargetIsMet: boolean,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        _target: number | BN | string,
        _minimumContribution: number | BN | string,
        _duration: number | BN | string,
        _goalType: number | BN | string,
        _token: string,
        _allowContributionAfterTargetIsMet: boolean,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    /**
     * Extends campaign contribution deadline
     * @param _time How long until the campaign stops receiving contributions
     */
    extendDeadline: {
      (
        _time: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<Truffle.TransactionResponse<AllEvents>>;
      call(
        _time: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        _time: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        _time: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    /**
     * Sets the number of times the campaign owner can extended deadlines. Restricted to factory
     * @param _count Number of times a campaign owner can extend the deadline
     */
    setDeadlineSetTimes: {
      (
        _count: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<Truffle.TransactionResponse<AllEvents>>;
      call(
        _count: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        _count: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        _count: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    /**
     * Contribute method enables a user become an approver in the campaign
     * @param _rewardId Reward unique id
     * @param _token Address of token to be used for transactions by default
     * @param _withReward Indicates if the user wants a reward alongside their contribution
     */
    contribute: {
      (
        _token: string,
        _rewardId: number | BN | string,
        _withReward: boolean,
        txDetails?: Truffle.TransactionDetails
      ): Promise<Truffle.TransactionResponse<AllEvents>>;
      call(
        _token: string,
        _rewardId: number | BN | string,
        _withReward: boolean,
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        _token: string,
        _rewardId: number | BN | string,
        _withReward: boolean,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        _token: string,
        _rewardId: number | BN | string,
        _withReward: boolean,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    /**
     * Allows withdrawal of contribution by a user, works if campaign target isn't met
     * @param _wallet Address where amount is delivered
     */
    withdrawOwnContribution: {
      (_wallet: string, txDetails?: Truffle.TransactionDetails): Promise<
        Truffle.TransactionResponse<AllEvents>
      >;
      call(
        _wallet: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        _wallet: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        _wallet: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    /**
     * Allows withdrawal of balance by factory on behalf of a user.  Cases where users wallet is compromised
     * @param _user User whose funds are being requested
     * @param _wallet Address where amount is delivered
     */
    withdrawContributionForUser: {
      (
        _user: string,
        _wallet: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<Truffle.TransactionResponse<AllEvents>>;
      call(
        _user: string,
        _wallet: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        _user: string,
        _wallet: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        _user: string,
        _wallet: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    /**
     * Used to measure user funds left after request finalizations
     * @param _user Address of user check is carried out on
     */
    userContributionLoss(
      _user: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<BN>;

    /**
     * Creates a formal request to withdraw funds from user contributions called by the campagn manager or factory Restricted unless target is met and deadline is expired
     * @param _duration Duration until users aren't able to vote on the request
     * @param _recipient Address where requested funds are deposited
     * @param _value Amount being requested by the campaign manager
     */
    createRequest: {
      (
        _recipient: string,
        _value: number | BN | string,
        _duration: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<Truffle.TransactionResponse<AllEvents>>;
      call(
        _recipient: string,
        _value: number | BN | string,
        _duration: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        _recipient: string,
        _value: number | BN | string,
        _duration: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        _recipient: string,
        _value: number | BN | string,
        _duration: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    /**
     * Renders a request void and useless
     * @param _requestId ID of request being voided
     */
    voidRequest: {
      (
        _requestId: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<Truffle.TransactionResponse<AllEvents>>;
      call(
        _requestId: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        _requestId: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        _requestId: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    /**
     * Approvers only method which approves spending request issued by the campaign manager or factory
     * @param _requestId ID of request being voted on
     * @param _support An integer of 0 for against, 1 for in-favor, and 2 for abstain
     */
    voteOnRequest: {
      (
        _requestId: number | BN | string,
        _support: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<Truffle.TransactionResponse<AllEvents>>;
      call(
        _requestId: number | BN | string,
        _support: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        _requestId: number | BN | string,
        _support: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        _requestId: number | BN | string,
        _support: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    /**
     * Approvers only method which cancels initial vote on a request
     * @param _requestId ID of request being voted on
     */
    cancelVote: {
      (
        _requestId: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<Truffle.TransactionResponse<AllEvents>>;
      call(
        _requestId: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        _requestId: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        _requestId: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    /**
     * Withdrawal method called only when a request receives the right amount votes
     * @param _requestId ID of request being withdrawn
     */
    finalizeRequest: {
      (
        _requestId: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<Truffle.TransactionResponse<AllEvents>>;
      call(
        _requestId: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        _requestId: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        _requestId: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    /**
     * Pauses the campaign and switches `campaignState` to `REVIEW` indicating it's ready to be reviewd by it's approvers after the campaign is over
     */
    reviewMode: {
      (txDetails?: Truffle.TransactionDetails): Promise<
        Truffle.TransactionResponse<AllEvents>
      >;
      call(txDetails?: Truffle.TransactionDetails): Promise<void>;
      sendTransaction(txDetails?: Truffle.TransactionDetails): Promise<string>;
      estimateGas(txDetails?: Truffle.TransactionDetails): Promise<number>;
    };

    /**
     * User acknowledgement of review state enabled by the campaign owner
     */
    reviewCampaignPerformance: {
      (txDetails?: Truffle.TransactionDetails): Promise<
        Truffle.TransactionResponse<AllEvents>
      >;
      call(txDetails?: Truffle.TransactionDetails): Promise<void>;
      sendTransaction(txDetails?: Truffle.TransactionDetails): Promise<string>;
      estimateGas(txDetails?: Truffle.TransactionDetails): Promise<number>;
    };

    /**
     * Called by campaign manager to mark the campaign as complete right after it secured enough reviews from users
     */
    markCampaignComplete: {
      (txDetails?: Truffle.TransactionDetails): Promise<
        Truffle.TransactionResponse<AllEvents>
      >;
      call(txDetails?: Truffle.TransactionDetails): Promise<void>;
      sendTransaction(txDetails?: Truffle.TransactionDetails): Promise<string>;
      estimateGas(txDetails?: Truffle.TransactionDetails): Promise<number>;
    };

    /**
     * Called by an approver to report a campaign to factory. Campaign must be in collection or live state
     */
    reportCampaign: {
      (txDetails?: Truffle.TransactionDetails): Promise<
        Truffle.TransactionResponse<AllEvents>
      >;
      call(txDetails?: Truffle.TransactionDetails): Promise<void>;
      sendTransaction(txDetails?: Truffle.TransactionDetails): Promise<string>;
      estimateGas(txDetails?: Truffle.TransactionDetails): Promise<number>;
    };

    /**
     * Changes campaign state
     */
    setCampaignState: {
      (
        _state: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<Truffle.TransactionResponse<AllEvents>>;
      call(
        _state: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        _state: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        _state: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    /**
     * Pauses or Unpauses withdrawals depending on state passed in argument
     * @param _state Indicates pause or unpause state
     */
    toggleWithdrawalState: {
      (_state: boolean, txDetails?: Truffle.TransactionDetails): Promise<
        Truffle.TransactionResponse<AllEvents>
      >;
      call(
        _state: boolean,
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        _state: boolean,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        _state: boolean,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    /**
     * Unpauses the campaign, transactions in the campaign resume per usual
     */
    unpauseCampaign: {
      (txDetails?: Truffle.TransactionDetails): Promise<
        Truffle.TransactionResponse<AllEvents>
      >;
      call(txDetails?: Truffle.TransactionDetails): Promise<void>;
      sendTransaction(txDetails?: Truffle.TransactionDetails): Promise<string>;
      estimateGas(txDetails?: Truffle.TransactionDetails): Promise<number>;
    };

    /**
     * Pauses the campaign, it halts all transactions in the campaign
     */
    pauseCampaign: {
      (txDetails?: Truffle.TransactionDetails): Promise<
        Truffle.TransactionResponse<AllEvents>
      >;
      call(txDetails?: Truffle.TransactionDetails): Promise<void>;
      sendTransaction(txDetails?: Truffle.TransactionDetails): Promise<string>;
      estimateGas(txDetails?: Truffle.TransactionDetails): Promise<number>;
    };
  };

  getPastEvents(event: string): Promise<EventData[]>;
  getPastEvents(
    event: string,
    options: PastEventOptions,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
  getPastEvents(event: string, options: PastEventOptions): Promise<EventData[]>;
  getPastEvents(
    event: string,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
}
