/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { EventData, PastEventOptions } from "web3-eth-contract";

export interface CampaignRewardsContract
  extends Truffle.Contract<CampaignRewardsInstance> {
  "new"(meta?: Truffle.TransactionDetails): Promise<CampaignRewardsInstance>;
}

export interface CampaignRewardOwnerSet {
  name: "CampaignRewardOwnerSet";
  args: {
    campaignId: BN;
    owner: string;
    sender: string;
    0: BN;
    1: string;
    2: string;
  };
}

export interface RewardCreated {
  name: "RewardCreated";
  args: {
    rewardId: BN;
    campaignId: BN;
    value: BN;
    deliveryDate: BN;
    stock: BN;
    active: boolean;
    sender: string;
    0: BN;
    1: BN;
    2: BN;
    3: BN;
    4: BN;
    5: boolean;
    6: string;
  };
}

export interface RewardDestroyed {
  name: "RewardDestroyed";
  args: {
    rewardId: BN;
    campaignId: BN;
    sender: string;
    0: BN;
    1: BN;
    2: string;
  };
}

export interface RewardModified {
  name: "RewardModified";
  args: {
    rewardId: BN;
    campaignId: BN;
    value: BN;
    deliveryDate: BN;
    stock: BN;
    active: boolean;
    sender: string;
    0: BN;
    1: BN;
    2: BN;
    3: BN;
    4: BN;
    5: boolean;
    6: string;
  };
}

export interface RewardRecipientAdded {
  name: "RewardRecipientAdded";
  args: {
    rewardId: BN;
    campaignId: BN;
    amount: BN;
    sender: string;
    0: BN;
    1: BN;
    2: BN;
    3: string;
  };
}

export interface RewardRecipientApproval {
  name: "RewardRecipientApproval";
  args: {
    rewardRecipientId: BN;
    campaignId: BN;
    sender: string;
    0: BN;
    1: BN;
    2: string;
  };
}

export interface RewardStockIncreased {
  name: "RewardStockIncreased";
  args: {
    rewardId: BN;
    campaignId: BN;
    count: BN;
    sender: string;
    0: BN;
    1: BN;
    2: BN;
    3: string;
  };
}

export interface RewarderApproval {
  name: "RewarderApproval";
  args: {
    rewardRecipientId: BN;
    campaignId: BN;
    status: boolean;
    sender: string;
    0: BN;
    1: BN;
    2: boolean;
    3: string;
  };
}

export interface RoleAdminChanged {
  name: "RoleAdminChanged";
  args: {
    role: string;
    previousAdminRole: string;
    newAdminRole: string;
    0: string;
    1: string;
    2: string;
  };
}

export interface RoleGranted {
  name: "RoleGranted";
  args: {
    role: string;
    account: string;
    sender: string;
    0: string;
    1: string;
    2: string;
  };
}

export interface RoleRevoked {
  name: "RoleRevoked";
  args: {
    role: string;
    account: string;
    sender: string;
    0: string;
    1: string;
    2: string;
  };
}

type AllEvents =
  | CampaignRewardOwnerSet
  | RewardCreated
  | RewardDestroyed
  | RewardModified
  | RewardRecipientAdded
  | RewardRecipientApproval
  | RewardStockIncreased
  | RewarderApproval
  | RoleAdminChanged
  | RoleGranted
  | RoleRevoked;

export interface CampaignRewardsInstance extends Truffle.ContractInstance {
  DEFAULT_ADMIN_ROLE(txDetails?: Truffle.TransactionDetails): Promise<string>;

  campaignID(txDetails?: Truffle.TransactionDetails): Promise<BN>;

  /**
   * Returns the admin role that controls `role`. See {grantRole} and {revokeRole}. To change a role's admin, use {_setRoleAdmin}.
   */
  getRoleAdmin(
    role: string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<string>;

  /**
   * Grants `role` to `account`. If `account` had not been already granted `role`, emits a {RoleGranted} event. Requirements: - the caller must have ``role``'s admin role.
   */
  grantRole: {
    (
      role: string,
      account: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse<AllEvents>>;
    call(
      role: string,
      account: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      role: string,
      account: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      role: string,
      account: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  /**
   * Returns `true` if `account` has been granted `role`.
   */
  hasRole(
    role: string,
    account: string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<boolean>;

  /**
   * Revokes `role` from the calling account. Roles are often managed via {grantRole} and {revokeRole}: this function's purpose is to provide a mechanism for accounts to lose their privileges if they are compromised (such as when a trusted device is misplaced). If the calling account had been granted `role`, emits a {RoleRevoked} event. Requirements: - the caller must be `account`.
   */
  renounceRole: {
    (
      role: string,
      account: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse<AllEvents>>;
    call(
      role: string,
      account: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      role: string,
      account: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      role: string,
      account: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  /**
   * Revokes `role` from `account`. If `account` had been granted `role`, emits a {RoleRevoked} event. Requirements: - the caller must have ``role``'s admin role.
   */
  revokeRole: {
    (
      role: string,
      account: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse<AllEvents>>;
    call(
      role: string,
      account: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      role: string,
      account: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      role: string,
      account: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  rewardRecipients(
    arg0: number | BN | string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<{ 0: BN; 1: string; 2: boolean; 3: boolean }>;

  rewardToRewardRecipientCount(
    arg0: number | BN | string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<BN>;

  rewards(
    arg0: number | BN | string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<{ 0: BN; 1: BN; 2: BN; 3: boolean; 4: boolean }>;

  root(txDetails?: Truffle.TransactionDetails): Promise<string>;

  /**
   * See {IERC165-supportsInterface}.
   */
  supportsInterface(
    interfaceId: string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<boolean>;

  userRewardCount(
    arg0: string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<BN>;

  /**
   * Constructor
   * @param _campaignFactory Address of factory
   * @param _campaignId ID of campaign reward contract belongs to
   * @param _root Address of campaign owner
   */
  __CampaignRewards_init: {
    (
      _campaignFactory: string,
      _root: string,
      _campaignId: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse<AllEvents>>;
    call(
      _campaignFactory: string,
      _root: string,
      _campaignId: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      _campaignFactory: string,
      _root: string,
      _campaignId: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      _campaignFactory: string,
      _root: string,
      _campaignId: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  /**
   * Creates rewards contributors can attain
   * @param _active Indicates if contributors can attain the reward
   * @param _deliveryDate Time in which reward will be deliverd to contriutors
   * @param _stock Quantity available for dispatch
   * @param _value Reward cost
   */
  createReward: {
    (
      _value: number | BN | string,
      _deliveryDate: number | BN | string,
      _stock: number | BN | string,
      _active: boolean,
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse<AllEvents>>;
    call(
      _value: number | BN | string,
      _deliveryDate: number | BN | string,
      _stock: number | BN | string,
      _active: boolean,
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      _value: number | BN | string,
      _deliveryDate: number | BN | string,
      _stock: number | BN | string,
      _active: boolean,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      _value: number | BN | string,
      _deliveryDate: number | BN | string,
      _stock: number | BN | string,
      _active: boolean,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  /**
   * Assigns a reward to a user after payment from parent contract Campaign
   * @param _amount Amount being paid by the user
   * @param _rewardId ID of the reward being assigned
   * @param _user Address of user reward is being assigned to
   */
  assignReward: {
    (
      _rewardId: number | BN | string,
      _amount: number | BN | string,
      _user: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse<AllEvents>>;
    call(
      _rewardId: number | BN | string,
      _amount: number | BN | string,
      _user: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      _rewardId: number | BN | string,
      _amount: number | BN | string,
      _user: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      _rewardId: number | BN | string,
      _amount: number | BN | string,
      _user: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  /**
   * Modifies a reward by id
   * @param _active Indicates if contributors can attain the reward
   * @param _deliveryDate Time in which reward will be deliverd to contriutors
   * @param _rewardId Reward unique id
   * @param _stock Quantity available for dispatch
   * @param _value Reward cost
   */
  modifyReward: {
    (
      _rewardId: number | BN | string,
      _value: number | BN | string,
      _deliveryDate: number | BN | string,
      _stock: number | BN | string,
      _active: boolean,
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse<AllEvents>>;
    call(
      _rewardId: number | BN | string,
      _value: number | BN | string,
      _deliveryDate: number | BN | string,
      _stock: number | BN | string,
      _active: boolean,
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      _rewardId: number | BN | string,
      _value: number | BN | string,
      _deliveryDate: number | BN | string,
      _stock: number | BN | string,
      _active: boolean,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      _rewardId: number | BN | string,
      _value: number | BN | string,
      _deliveryDate: number | BN | string,
      _stock: number | BN | string,
      _active: boolean,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  /**
   * Increases a reward stock count
   * @param _count Stock count to increase by
   * @param _rewardId Reward unique id
   */
  increaseRewardStock: {
    (
      _rewardId: number | BN | string,
      _count: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse<AllEvents>>;
    call(
      _rewardId: number | BN | string,
      _count: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      _rewardId: number | BN | string,
      _count: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      _rewardId: number | BN | string,
      _count: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  /**
   * Deletes a reward by id
   * @param _rewardId Reward unique id
   */
  destroyReward: {
    (
      _rewardId: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse<AllEvents>>;
    call(
      _rewardId: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      _rewardId: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      _rewardId: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  /**
   * Called by the campaign owner to indicate they delivered the reward to the rewardRecipient
   * @param _rewardRecipientId ID to struct containing reward and user to be rewarded
   * @param _status Indicates if the delivery was successful or not
   */
  campaignSentReward: {
    (
      _rewardRecipientId: number | BN | string,
      _status: boolean,
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse<AllEvents>>;
    call(
      _rewardRecipientId: number | BN | string,
      _status: boolean,
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      _rewardRecipientId: number | BN | string,
      _status: boolean,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      _rewardRecipientId: number | BN | string,
      _status: boolean,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  /**
   * Called by a user eligible for rewards to indicate they received their reward
   * @param _rewardRecipientId ID to struct containing reward and user to be rewarded
   */
  userReceivedCampaignReward: {
    (
      _rewardRecipientId: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse<AllEvents>>;
    call(
      _rewardRecipientId: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      _rewardRecipientId: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      _rewardRecipientId: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  /**
   * Renounces rewards owned by the specified user
   * @param _user Address of user who rewards are being renounced
   */
  renounceRewards: {
    (_user: string, txDetails?: Truffle.TransactionDetails): Promise<
      Truffle.TransactionResponse<AllEvents>
    >;
    call(_user: string, txDetails?: Truffle.TransactionDetails): Promise<void>;
    sendTransaction(
      _user: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      _user: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  /**
   * Transfers rewards from the old owner to a new owner
   * @param _newAddress Address of new owner rewards are being transferred to
   * @param _oldAddress Address of previous owner of rewards
   */
  transferRewards: {
    (
      _oldAddress: string,
      _newAddress: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse<AllEvents>>;
    call(
      _oldAddress: string,
      _newAddress: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      _oldAddress: string,
      _newAddress: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      _oldAddress: string,
      _newAddress: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  methods: {
    DEFAULT_ADMIN_ROLE(txDetails?: Truffle.TransactionDetails): Promise<string>;

    campaignID(txDetails?: Truffle.TransactionDetails): Promise<BN>;

    /**
     * Returns the admin role that controls `role`. See {grantRole} and {revokeRole}. To change a role's admin, use {_setRoleAdmin}.
     */
    getRoleAdmin(
      role: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;

    /**
     * Grants `role` to `account`. If `account` had not been already granted `role`, emits a {RoleGranted} event. Requirements: - the caller must have ``role``'s admin role.
     */
    grantRole: {
      (
        role: string,
        account: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<Truffle.TransactionResponse<AllEvents>>;
      call(
        role: string,
        account: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        role: string,
        account: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        role: string,
        account: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    /**
     * Returns `true` if `account` has been granted `role`.
     */
    hasRole(
      role: string,
      account: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<boolean>;

    /**
     * Revokes `role` from the calling account. Roles are often managed via {grantRole} and {revokeRole}: this function's purpose is to provide a mechanism for accounts to lose their privileges if they are compromised (such as when a trusted device is misplaced). If the calling account had been granted `role`, emits a {RoleRevoked} event. Requirements: - the caller must be `account`.
     */
    renounceRole: {
      (
        role: string,
        account: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<Truffle.TransactionResponse<AllEvents>>;
      call(
        role: string,
        account: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        role: string,
        account: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        role: string,
        account: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    /**
     * Revokes `role` from `account`. If `account` had been granted `role`, emits a {RoleRevoked} event. Requirements: - the caller must have ``role``'s admin role.
     */
    revokeRole: {
      (
        role: string,
        account: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<Truffle.TransactionResponse<AllEvents>>;
      call(
        role: string,
        account: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        role: string,
        account: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        role: string,
        account: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    rewardRecipients(
      arg0: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<{ 0: BN; 1: string; 2: boolean; 3: boolean }>;

    rewardToRewardRecipientCount(
      arg0: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<BN>;

    rewards(
      arg0: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<{ 0: BN; 1: BN; 2: BN; 3: boolean; 4: boolean }>;

    root(txDetails?: Truffle.TransactionDetails): Promise<string>;

    /**
     * See {IERC165-supportsInterface}.
     */
    supportsInterface(
      interfaceId: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<boolean>;

    userRewardCount(
      arg0: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<BN>;

    /**
     * Constructor
     * @param _campaignFactory Address of factory
     * @param _campaignId ID of campaign reward contract belongs to
     * @param _root Address of campaign owner
     */
    __CampaignRewards_init: {
      (
        _campaignFactory: string,
        _root: string,
        _campaignId: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<Truffle.TransactionResponse<AllEvents>>;
      call(
        _campaignFactory: string,
        _root: string,
        _campaignId: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        _campaignFactory: string,
        _root: string,
        _campaignId: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        _campaignFactory: string,
        _root: string,
        _campaignId: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    /**
     * Creates rewards contributors can attain
     * @param _active Indicates if contributors can attain the reward
     * @param _deliveryDate Time in which reward will be deliverd to contriutors
     * @param _stock Quantity available for dispatch
     * @param _value Reward cost
     */
    createReward: {
      (
        _value: number | BN | string,
        _deliveryDate: number | BN | string,
        _stock: number | BN | string,
        _active: boolean,
        txDetails?: Truffle.TransactionDetails
      ): Promise<Truffle.TransactionResponse<AllEvents>>;
      call(
        _value: number | BN | string,
        _deliveryDate: number | BN | string,
        _stock: number | BN | string,
        _active: boolean,
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        _value: number | BN | string,
        _deliveryDate: number | BN | string,
        _stock: number | BN | string,
        _active: boolean,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        _value: number | BN | string,
        _deliveryDate: number | BN | string,
        _stock: number | BN | string,
        _active: boolean,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    /**
     * Assigns a reward to a user after payment from parent contract Campaign
     * @param _amount Amount being paid by the user
     * @param _rewardId ID of the reward being assigned
     * @param _user Address of user reward is being assigned to
     */
    assignReward: {
      (
        _rewardId: number | BN | string,
        _amount: number | BN | string,
        _user: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<Truffle.TransactionResponse<AllEvents>>;
      call(
        _rewardId: number | BN | string,
        _amount: number | BN | string,
        _user: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        _rewardId: number | BN | string,
        _amount: number | BN | string,
        _user: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        _rewardId: number | BN | string,
        _amount: number | BN | string,
        _user: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    /**
     * Modifies a reward by id
     * @param _active Indicates if contributors can attain the reward
     * @param _deliveryDate Time in which reward will be deliverd to contriutors
     * @param _rewardId Reward unique id
     * @param _stock Quantity available for dispatch
     * @param _value Reward cost
     */
    modifyReward: {
      (
        _rewardId: number | BN | string,
        _value: number | BN | string,
        _deliveryDate: number | BN | string,
        _stock: number | BN | string,
        _active: boolean,
        txDetails?: Truffle.TransactionDetails
      ): Promise<Truffle.TransactionResponse<AllEvents>>;
      call(
        _rewardId: number | BN | string,
        _value: number | BN | string,
        _deliveryDate: number | BN | string,
        _stock: number | BN | string,
        _active: boolean,
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        _rewardId: number | BN | string,
        _value: number | BN | string,
        _deliveryDate: number | BN | string,
        _stock: number | BN | string,
        _active: boolean,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        _rewardId: number | BN | string,
        _value: number | BN | string,
        _deliveryDate: number | BN | string,
        _stock: number | BN | string,
        _active: boolean,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    /**
     * Increases a reward stock count
     * @param _count Stock count to increase by
     * @param _rewardId Reward unique id
     */
    increaseRewardStock: {
      (
        _rewardId: number | BN | string,
        _count: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<Truffle.TransactionResponse<AllEvents>>;
      call(
        _rewardId: number | BN | string,
        _count: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        _rewardId: number | BN | string,
        _count: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        _rewardId: number | BN | string,
        _count: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    /**
     * Deletes a reward by id
     * @param _rewardId Reward unique id
     */
    destroyReward: {
      (
        _rewardId: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<Truffle.TransactionResponse<AllEvents>>;
      call(
        _rewardId: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        _rewardId: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        _rewardId: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    /**
     * Called by the campaign owner to indicate they delivered the reward to the rewardRecipient
     * @param _rewardRecipientId ID to struct containing reward and user to be rewarded
     * @param _status Indicates if the delivery was successful or not
     */
    campaignSentReward: {
      (
        _rewardRecipientId: number | BN | string,
        _status: boolean,
        txDetails?: Truffle.TransactionDetails
      ): Promise<Truffle.TransactionResponse<AllEvents>>;
      call(
        _rewardRecipientId: number | BN | string,
        _status: boolean,
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        _rewardRecipientId: number | BN | string,
        _status: boolean,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        _rewardRecipientId: number | BN | string,
        _status: boolean,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    /**
     * Called by a user eligible for rewards to indicate they received their reward
     * @param _rewardRecipientId ID to struct containing reward and user to be rewarded
     */
    userReceivedCampaignReward: {
      (
        _rewardRecipientId: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<Truffle.TransactionResponse<AllEvents>>;
      call(
        _rewardRecipientId: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        _rewardRecipientId: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        _rewardRecipientId: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    /**
     * Renounces rewards owned by the specified user
     * @param _user Address of user who rewards are being renounced
     */
    renounceRewards: {
      (_user: string, txDetails?: Truffle.TransactionDetails): Promise<
        Truffle.TransactionResponse<AllEvents>
      >;
      call(
        _user: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        _user: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        _user: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    /**
     * Transfers rewards from the old owner to a new owner
     * @param _newAddress Address of new owner rewards are being transferred to
     * @param _oldAddress Address of previous owner of rewards
     */
    transferRewards: {
      (
        _oldAddress: string,
        _newAddress: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<Truffle.TransactionResponse<AllEvents>>;
      call(
        _oldAddress: string,
        _newAddress: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        _oldAddress: string,
        _newAddress: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        _oldAddress: string,
        _newAddress: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };
  };

  getPastEvents(event: string): Promise<EventData[]>;
  getPastEvents(
    event: string,
    options: PastEventOptions,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
  getPastEvents(event: string, options: PastEventOptions): Promise<EventData[]>;
  getPastEvents(
    event: string,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
}
