/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { EventData, PastEventOptions } from "web3-eth-contract";

export interface ICampaignContract extends Truffle.Contract<ICampaignInstance> {
  "new"(meta?: Truffle.TransactionDetails): Promise<ICampaignInstance>;
}

type AllEvents = never;

export interface ICampaignInstance extends Truffle.ContractInstance {
  approvers(
    arg0: string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<boolean>;

  campaignID(txDetails?: Truffle.TransactionDetails): Promise<BN>;

  root(txDetails?: Truffle.TransactionDetails): Promise<string>;

  methods: {
    approvers(
      arg0: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<boolean>;

    campaignID(txDetails?: Truffle.TransactionDetails): Promise<BN>;

    root(txDetails?: Truffle.TransactionDetails): Promise<string>;
  };

  getPastEvents(event: string): Promise<EventData[]>;
  getPastEvents(
    event: string,
    options: PastEventOptions,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
  getPastEvents(event: string, options: PastEventOptions): Promise<EventData[]>;
  getPastEvents(
    event: string,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
}
