/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { AccessControlContract } from "./AccessControl";
import { AccessControlUpgradeableContract } from "./AccessControlUpgradeable";
import { CampaignContract } from "./Campaign";
import { CampaignFactoryContract } from "./CampaignFactory";
import { CampaignFactoryInterfaceContract } from "./CampaignFactoryInterface";
import { CampaignInterfaceContract } from "./CampaignInterface";
import { CampaignRequestContract } from "./CampaignRequest";
import { CampaignRewardContract } from "./CampaignReward";
import { CampaignRewardInterfaceContract } from "./CampaignRewardInterface";
import { CampaignRewardsContract } from "./CampaignRewards";
import { CampaignVoteContract } from "./CampaignVote";
import { ERC165UpgradeableContract } from "./ERC165Upgradeable";
import { ERC20UpgradeableContract } from "./ERC20Upgradeable";
import { FactoryContract } from "./Factory";
import { IAccessControlUpgradeableContract } from "./IAccessControlUpgradeable";
import { ICampaignContract } from "./ICampaign";
import { ICampaignFactoryContract } from "./ICampaignFactory";
import { ICampaignRequestContract } from "./ICampaignRequest";
import { ICampaignRewardContract } from "./ICampaignReward";
import { IERC165UpgradeableContract } from "./IERC165Upgradeable";
import { IERC20MetadataUpgradeableContract } from "./IERC20MetadataUpgradeable";
import { IERC20UpgradeableContract } from "./IERC20Upgradeable";
import { IRewardContract } from "./IReward";
import { MigrationsContract } from "./Migrations";
import { PausableUpgradeableContract } from "./PausableUpgradeable";
import { TestTokenContract } from "./TestToken";

declare global {
  namespace Truffle {
    interface Artifacts {
      require(name: "AccessControl"): AccessControlContract;
      require(
        name: "AccessControlUpgradeable"
      ): AccessControlUpgradeableContract;
      require(name: "Campaign"): CampaignContract;
      require(name: "CampaignFactory"): CampaignFactoryContract;
      require(
        name: "CampaignFactoryInterface"
      ): CampaignFactoryInterfaceContract;
      require(name: "CampaignInterface"): CampaignInterfaceContract;
      require(name: "CampaignRequest"): CampaignRequestContract;
      require(name: "CampaignReward"): CampaignRewardContract;
      require(name: "CampaignRewardInterface"): CampaignRewardInterfaceContract;
      require(name: "CampaignRewards"): CampaignRewardsContract;
      require(name: "CampaignVote"): CampaignVoteContract;
      require(name: "ERC165Upgradeable"): ERC165UpgradeableContract;
      require(name: "ERC20Upgradeable"): ERC20UpgradeableContract;
      require(name: "Factory"): FactoryContract;
      require(
        name: "IAccessControlUpgradeable"
      ): IAccessControlUpgradeableContract;
      require(name: "ICampaign"): ICampaignContract;
      require(name: "ICampaignFactory"): ICampaignFactoryContract;
      require(name: "ICampaignRequest"): ICampaignRequestContract;
      require(name: "ICampaignReward"): ICampaignRewardContract;
      require(name: "IERC165Upgradeable"): IERC165UpgradeableContract;
      require(
        name: "IERC20MetadataUpgradeable"
      ): IERC20MetadataUpgradeableContract;
      require(name: "IERC20Upgradeable"): IERC20UpgradeableContract;
      require(name: "IReward"): IRewardContract;
      require(name: "Migrations"): MigrationsContract;
      require(name: "PausableUpgradeable"): PausableUpgradeableContract;
      require(name: "TestToken"): TestTokenContract;
    }
  }
}

export { AccessControlContract, AccessControlInstance } from "./AccessControl";
export {
  AccessControlUpgradeableContract,
  AccessControlUpgradeableInstance,
} from "./AccessControlUpgradeable";
export { CampaignContract, CampaignInstance } from "./Campaign";
export {
  CampaignFactoryContract,
  CampaignFactoryInstance,
} from "./CampaignFactory";
export {
  CampaignFactoryInterfaceContract,
  CampaignFactoryInterfaceInstance,
} from "./CampaignFactoryInterface";
export {
  CampaignInterfaceContract,
  CampaignInterfaceInstance,
} from "./CampaignInterface";
export {
  CampaignRequestContract,
  CampaignRequestInstance,
} from "./CampaignRequest";
export {
  CampaignRewardContract,
  CampaignRewardInstance,
} from "./CampaignReward";
export {
  CampaignRewardInterfaceContract,
  CampaignRewardInterfaceInstance,
} from "./CampaignRewardInterface";
export {
  CampaignRewardsContract,
  CampaignRewardsInstance,
} from "./CampaignRewards";
export { CampaignVoteContract, CampaignVoteInstance } from "./CampaignVote";
export {
  ERC165UpgradeableContract,
  ERC165UpgradeableInstance,
} from "./ERC165Upgradeable";
export {
  ERC20UpgradeableContract,
  ERC20UpgradeableInstance,
} from "./ERC20Upgradeable";
export { FactoryContract, FactoryInstance } from "./Factory";
export {
  IAccessControlUpgradeableContract,
  IAccessControlUpgradeableInstance,
} from "./IAccessControlUpgradeable";
export { ICampaignContract, ICampaignInstance } from "./ICampaign";
export {
  ICampaignFactoryContract,
  ICampaignFactoryInstance,
} from "./ICampaignFactory";
export {
  ICampaignRequestContract,
  ICampaignRequestInstance,
} from "./ICampaignRequest";
export {
  ICampaignRewardContract,
  ICampaignRewardInstance,
} from "./ICampaignReward";
export {
  IERC165UpgradeableContract,
  IERC165UpgradeableInstance,
} from "./IERC165Upgradeable";
export {
  IERC20MetadataUpgradeableContract,
  IERC20MetadataUpgradeableInstance,
} from "./IERC20MetadataUpgradeable";
export {
  IERC20UpgradeableContract,
  IERC20UpgradeableInstance,
} from "./IERC20Upgradeable";
export { IRewardContract, IRewardInstance } from "./IReward";
export { MigrationsContract, MigrationsInstance } from "./Migrations";
export {
  PausableUpgradeableContract,
  PausableUpgradeableInstance,
} from "./PausableUpgradeable";
export { TestTokenContract, TestTokenInstance } from "./TestToken";
